- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/dotfiles.yml
