- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p /home/oj/.local/.npm-global
  tags:
    - install
    - node

- name: add npmjs to path
  shell: PATH=/home/oj/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '/home/oj/.local/.npm-global'
  tags:
    - install
    - node

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=/home/oj/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node
    - npm-path

- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Make N cache folder
  shell: mkdir -p /usr/local/n
  become: true
  tags:
    - install
    - node

- name: Take ownership of N cache folder
  shell: chown -R $(whoami) /usr/local/n
  become: true
  tags:
    - install
    - node

- name: Make sure required folders exists
  shell: mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: true
  tags:
    - install
    - node

- name: Take ownership of required destination folders
  shell: chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: true
  tags:
    - install
    - node

- name: Install correct version of Node
  become: true
  shell: n 14
  tags:
    - install
    - node
