- name: Create NPM global folder
  shell: mkdir -p ~/.npm-global
  tags:
    - install
    - node

- name: Set NPM global packages folder
  shell: npm config set prefix '~/.npm-global'
  tags:
    - install
    - node

- name: Add NPM global do path
  shell: PATH=~/.npm-global/bin:$PATH
  tags:
    - install
    - node

- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Make N cache folder
  shell: mkdir -p /usr/local/n
  become: true
  tags:
    - install
    - node

- name: Take ownership of N cache folder
  shell: chown -R $(whoami) /usr/local/n
  become: true
  tags:
    - install
    - node

- name: Make sure required folders exists
  shell: mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: true
  tags:
    - install
    - node

- name: Take ownership of required destination folders
  shell: chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: true
  tags:
    - install
    - node

- name: Install correct version of Node
  shell: n 14
  tags:
    - install
    - node
